// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASo1ReA1cunzp5ZwE5Dk18jaTz8G81Hh0',
    appId: '1:666703071106:web:024e1df67accf50072719b',
    messagingSenderId: '666703071106',
    projectId: 'e-commerceapp-38a65',
    authDomain: 'e-commerceapp-38a65.firebaseapp.com',
    storageBucket: 'e-commerceapp-38a65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCn234KKel1kIKzZy5f4hNuBPLTBWYOu8',
    appId: '1:666703071106:android:1709df61a8efa94372719b',
    messagingSenderId: '666703071106',
    projectId: 'e-commerceapp-38a65',
    storageBucket: 'e-commerceapp-38a65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSYLNElQM3DZH1QwTjZdKVoambeCo67NM',
    appId: '1:666703071106:ios:5528e6d392d49c5672719b',
    messagingSenderId: '666703071106',
    projectId: 'e-commerceapp-38a65',
    storageBucket: 'e-commerceapp-38a65.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
